2024-08-03 13:23:24,084 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:23:26,231 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:23:27,072 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 13:24:13,483 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\connection.py changed, reloading.
2024-08-03 13:24:16,082 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:24:16,963 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 13:25:07,273 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:25:14,371 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:25:14,960 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 13:28:15,623 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-03 13:28:20,531 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:28:21,217 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 13:28:32,076 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-03 13:28:34,549 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 13:28:35,134 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 13:30:06,261 - django.request - WARNING - Unauthorized: /api/upload_resume/
2024-08-03 13:30:53,857 - root - INFO - Job 64d02b07-552d-4bb5-9d49-b4992645b316 added to the queue
2024-08-03 13:31:01,802 - root - INFO - Job 64d02b07-552d-4bb5-9d49-b4992645b316 status updated to processing
2024-08-03 13:31:31,896 - root - INFO - Job 64d02b07-552d-4bb5-9d49-b4992645b316 status updated to processing
2024-08-03 13:31:44,555 - root - INFO - Job 64d02b07-552d-4bb5-9d49-b4992645b316 marked as complete in the database.
2024-08-03 13:32:01,836 - root - INFO - Job 64d02b07-552d-4bb5-9d49-b4992645b316 is completed and removed from the queue
2024-08-03 19:27:40,622 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 19:27:43,923 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 19:27:44,651 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 19:28:06,298 - root - INFO - Job da647733-d4e2-48f8-8807-62ab4c1d5a78 added to the queue
2024-08-03 19:28:29,788 - root - INFO - Job da647733-d4e2-48f8-8807-62ab4c1d5a78 status updated to processing
2024-08-03 19:28:49,724 - root - INFO - Job da647733-d4e2-48f8-8807-62ab4c1d5a78 marked as complete in the database.
2024-08-03 19:28:59,798 - root - INFO - Job da647733-d4e2-48f8-8807-62ab4c1d5a78 is completed and removed from the queue
2024-08-03 19:40:47,822 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 19:40:50,461 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 19:40:51,068 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-03 19:43:39,350 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\tasks.py changed, reloading.
2024-08-03 19:43:42,229 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-03 19:43:42,816 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 16:04:15,962 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 16:04:24,855 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 16:04:25,648 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:20:36,722 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:20:40,713 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:25:14,203 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:25:17,083 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:25:17,789 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:25:29,678 - accounts.tasks - INFO - Confirmation email sent to adavadkardhruv@gmail.com
2024-08-05 19:28:32,408 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:28:37,666 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:28:38,746 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:28:44,547 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:28:47,990 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:28:49,124 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:28:56,233 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:28:58,378 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:28:59,246 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:29:06,093 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:29:08,183 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:29:08,879 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:29:19,255 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:29:24,220 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:29:25,077 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:29:41,502 - django.request - WARNING - Bad Request: /api/signup/
2024-08-05 19:30:29,703 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:30:34,359 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:30:35,114 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:30:40,802 - django.request - WARNING - Bad Request: /api/signup/
2024-08-05 19:37:18,937 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:37:21,373 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:37:21,953 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:37:58,206 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:38:01,487 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:38:02,801 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:38:07,785 - django.request - WARNING - Bad Request: /api/signup/
2024-08-05 19:38:37,452 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:40:06,765 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:40:09,454 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:40:09,990 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:40:21,952 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 93, in login_view
    "message": error_message
               ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'error_message' where it is not associated with a value
2024-08-05 19:40:32,557 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:40:37,265 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:40:38,196 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:40:43,238 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:40:45,521 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:40:46,066 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:40:50,310 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 96, in login_view
    response.set_cookie('refresh_token', refresh_token, httponly=True, secure=True)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'set_cookie'
2024-08-05 19:41:20,815 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:41:25,006 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:41:25,831 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:42:01,143 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:42:05,182 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:42:05,660 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:42:12,144 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 96, in login_view
    response.set_cookie('refresh_token', refresh_token, httponly=True, secure=True)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'set_cookie'
2024-08-05 19:42:14,018 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 96, in login_view
    response.set_cookie('refresh_token', refresh_token, httponly=True, secure=True)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'set_cookie'
2024-08-05 19:42:18,745 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 96, in login_view
    response.set_cookie('refresh_token', refresh_token, httponly=True, secure=True)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'set_cookie'
2024-08-05 19:42:33,460 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:45:21,953 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:45:24,178 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:45:24,899 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:45:33,565 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 90, in login_view
    "status_code": status.status.HTTP_200_OK,
                   ^^^^^^^^^^^^^
AttributeError: module 'rest_framework.status' has no attribute 'status'
2024-08-05 19:45:45,014 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:45:45,941 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 84, in login_view
    user = User.objects.filter(candidate_email=candidate_email).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 692, in __getitem__
    for doc in clone:
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1514, in _retryable_read
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1335, in _select_server
    topology = self._get_topology()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1295, in _get_topology
    self._topology.open()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 175, in open
    self._ensure_opened()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 570, in _ensure_opened
    server.open()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\server.py", line 50, in open
    self._monitor.open()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\monitor.py", line 84, in open
    self._executor.open()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\periodic_executor.py", line 87, in open
    thread.start()
  File "C:\Python312\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
2024-08-05 19:45:48,608 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:45:49,156 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:49:50,634 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:49:53,380 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:49:54,020 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:50:20,847 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:50:25,270 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:50:26,321 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:50:30,755 - django.request - WARNING - Bad Request: /api/login/
2024-08-05 19:51:52,781 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:51:55,491 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:51:56,098 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:52:02,065 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:52:04,964 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:52:05,551 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:52:10,727 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:52:13,598 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:52:14,199 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:52:21,645 - django.request - ERROR - Internal Server Error: /api/login/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 114, in login_view
    "candidate_email":candidate_email
                      ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'candidate_email' where it is not associated with a value
2024-08-05 19:53:00,943 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:53:03,712 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:53:04,953 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:53:38,082 - accounts.tasks - INFO - Confirmation email sent to adavadkardhru@gmail.com
2024-08-05 19:55:43,610 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:55:46,645 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:55:47,371 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:56:13,402 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:56:15,599 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:56:16,668 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:56:27,565 - django.request - ERROR - Internal Server Error: /api/signup/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 71, in signup_view
    response_data.pop('password', None)
    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'response_data' where it is not associated with a value
2024-08-05 19:56:49,993 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:56:53,837 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:56:54,447 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:57:02,209 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:57:04,513 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:57:05,043 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:57:09,816 - django.request - WARNING - Bad Request: /api/signup/
2024-08-05 19:57:23,622 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:57:26,426 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:57:27,403 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:57:49,009 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:57:53,526 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:57:54,350 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:57:58,886 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 19:58:03,336 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 19:58:04,184 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 19:58:09,012 - django.request - WARNING - Bad Request: /api/signup/
2024-08-05 20:00:37,517 - django.request - WARNING - Bad Request: /api/login/
2024-08-05 20:00:52,477 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:00:55,101 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:00:55,817 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:01:11,755 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:01:14,730 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:01:15,763 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:01:29,285 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:01:32,576 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:01:33,446 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:01:44,516 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:01:49,710 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:01:50,500 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:01:56,422 - django.request - WARNING - Bad Request: /api/login/
2024-08-05 20:02:10,314 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:02:10,519 - django.request - WARNING - Bad Request: /api/login/
2024-08-05 20:02:16,703 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:02:19,175 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:03:06,049 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:03:08,727 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:03:09,450 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:05:04,026 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:05:06,861 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:05:07,569 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:05:13,137 - django.request - WARNING - Bad Request: /api/login/
2024-08-05 20:05:21,850 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:05:24,362 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:05:25,016 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:05:37,216 - django.request - WARNING - Bad Request: /api/login/
2024-08-05 20:13:37,471 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:13:39,640 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:13:40,129 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:14:20,902 - django.request - ERROR - Internal Server Error: /api/refresh_token/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 211, in refresh_token_view
    return Response({response, access_token})
                    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
2024-08-05 20:15:01,949 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:15:07,560 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:15:08,779 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:15:34,876 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:15:37,987 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:15:38,541 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:15:50,460 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:15:53,034 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:15:53,577 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:18:19,325 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:18:22,156 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:18:23,030 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:20:04,530 - root - INFO - Job 0134e4fa-cfd5-4f1c-bdf6-fea48c32e50a added to the queue
2024-08-05 20:20:04,556 - root - INFO - Job 03705f04-508d-44d3-83a8-9621b0d1a3dd added to the queue
2024-08-05 20:20:04,628 - root - INFO - Job 0134e4fa-cfd5-4f1c-bdf6-fea48c32e50a status updated to processing
2024-08-05 20:20:22,814 - root - INFO - Job 03705f04-508d-44d3-83a8-9621b0d1a3dd status updated to processing
2024-08-05 20:20:34,676 - root - INFO - Job 0134e4fa-cfd5-4f1c-bdf6-fea48c32e50a status updated to processing
2024-08-05 20:20:53,134 - root - INFO - Job 03705f04-508d-44d3-83a8-9621b0d1a3dd status updated to processing
2024-08-05 20:21:04,691 - root - INFO - Job 0134e4fa-cfd5-4f1c-bdf6-fea48c32e50a timed out and removed from the queue
2024-08-05 20:21:23,019 - root - INFO - Job 03705f04-508d-44d3-83a8-9621b0d1a3dd timed out and removed from the queue
2024-08-05 20:23:39,943 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:23:42,254 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:23:42,904 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:24:00,127 - django.request - WARNING - Bad Request: /api/upload_resume/
2024-08-05 20:24:16,573 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:24:21,320 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:24:21,869 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:24:27,443 - django.request - WARNING - Bad Request: /api/upload_resume/
2024-08-05 20:26:52,969 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:26:55,728 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:26:56,270 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:27:59,935 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:28:02,295 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:28:02,849 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:28:12,724 - django.request - WARNING - Bad Request: /api/upload_resume/
2024-08-05 20:36:10,470 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:36:15,679 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:36:16,398 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:36:21,191 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:36:23,908 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:36:24,507 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:36:30,241 - django.request - WARNING - Bad Request: /api/upload_resume/
2024-08-05 20:38:29,046 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:38:31,524 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:38:32,024 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:38:43,948 - django.request - WARNING - Bad Request: /api/upload_resume/
2024-08-05 20:39:23,240 - root - INFO - Job cdd6fc43-aae1-4511-9726-6c96ae3a6510 added to the queue
2024-08-05 20:39:32,794 - root - INFO - Job cdd6fc43-aae1-4511-9726-6c96ae3a6510 status updated to processing
2024-08-05 20:39:53,565 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:39:56,214 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:39:57,114 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:41:27,773 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\serializers.py changed, reloading.
2024-08-05 20:41:30,231 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:41:30,744 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:42:16,510 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:42:19,317 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:42:19,970 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:42:39,608 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:42:43,970 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:42:45,967 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:43:22,705 - root - INFO - Job 65850d87-2a09-4201-9a5c-97ba0e5d8904 added to the queue
2024-08-05 20:43:24,086 - django.request - WARNING - Bad Request: /api/upload_resume/
2024-08-05 20:43:37,715 - root - INFO - Job 65850d87-2a09-4201-9a5c-97ba0e5d8904 status updated to processing
2024-08-05 20:44:07,811 - root - INFO - Job 65850d87-2a09-4201-9a5c-97ba0e5d8904 status updated to processing
2024-08-05 20:44:37,916 - root - INFO - Job 65850d87-2a09-4201-9a5c-97ba0e5d8904 timed out and removed from the queue
2024-08-05 20:45:26,814 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:45:31,860 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:45:32,539 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:45:45,645 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:45:48,598 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:45:49,499 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:46:02,931 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:46:06,006 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:46:06,609 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:47:10,416 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:47:13,083 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:47:14,023 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:47:20,002 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:47:30,680 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:47:31,348 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:47:40,370 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:47:42,847 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:47:43,429 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-05 20:47:50,937 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-05 20:47:55,811 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-05 20:47:57,307 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:19:51,943 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:19:56,524 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:19:57,504 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:20:02,684 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:20:06,249 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:20:07,017 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:20:17,768 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:20:20,013 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:20:20,568 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:20:27,070 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:20:29,432 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:20:30,590 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:20:34,778 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:20:37,364 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:20:37,921 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:20:41,148 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:20:43,251 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:20:43,997 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:20:47,409 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:20:49,493 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:20:50,057 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:21:05,573 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:21:07,735 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:21:08,234 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:21:13,647 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:21:16,635 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:21:17,246 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:21:26,254 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:21:28,670 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:21:29,187 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:21:51,153 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:21:53,838 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:21:54,467 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:22:03,475 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:22:06,825 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:22:07,604 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:22:23,996 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:22:26,106 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:22:26,781 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:22:33,397 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:22:35,982 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:22:36,706 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:22:43,003 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:22:45,425 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:22:46,008 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:22:50,580 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:22:52,855 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:22:53,410 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:23:00,069 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:23:03,556 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:23:04,335 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:23:07,851 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:23:09,992 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:23:10,653 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:23:26,864 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:23:29,228 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:23:29,832 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:23:33,306 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:23:35,113 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:23:35,740 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:24:27,457 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:24:30,380 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:24:31,007 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:24:38,616 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:24:40,969 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:24:41,590 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:24:45,711 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:24:48,033 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:24:48,642 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:24:54,587 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:24:56,632 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:24:57,147 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:25:04,774 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:25:06,761 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:25:07,307 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:25:19,310 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:25:21,437 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:25:21,951 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:25:48,766 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:25:51,125 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:25:51,743 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:25:54,957 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:25:56,894 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:25:57,877 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:26:01,420 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:26:03,292 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:26:03,858 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:26:12,832 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:26:15,902 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:26:16,978 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:26:26,902 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:26:29,106 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:26:29,729 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:26:46,849 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:26:49,206 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:26:49,808 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:26:56,195 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:26:59,542 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:27:00,110 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:27:04,835 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:27:07,147 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:27:07,990 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:27:14,854 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:27:17,551 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:27:18,321 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:27:21,703 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:27:24,188 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:27:25,409 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:27:31,143 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 01:27:33,396 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 01:27:34,766 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 01:28:35,960 - root - INFO - Job be16ab58-a5c5-4e40-8a33-e86249c27ac1 added to the queue
2024-08-06 01:28:35,986 - root - INFO - Job d150ac08-25ab-4493-9b40-c2630a2d1f14 added to the queue
2024-08-06 01:28:36,044 - root - INFO - Job be16ab58-a5c5-4e40-8a33-e86249c27ac1 status updated to processing
2024-08-06 01:28:52,809 - root - INFO - Job d150ac08-25ab-4493-9b40-c2630a2d1f14 status updated to processing
2024-08-06 01:29:06,071 - root - INFO - Job be16ab58-a5c5-4e40-8a33-e86249c27ac1 status updated to processing
2024-08-06 01:29:11,647 - root - INFO - Job d150ac08-25ab-4493-9b40-c2630a2d1f14 marked as complete in the database.
2024-08-06 01:29:22,833 - root - INFO - Job d150ac08-25ab-4493-9b40-c2630a2d1f14 is completed and removed from the queue
2024-08-06 01:29:36,089 - root - INFO - Job be16ab58-a5c5-4e40-8a33-e86249c27ac1 timed out and removed from the queue
2024-08-06 12:46:17,294 - connection - ERROR - Error connecting to MongoDB: The resolution lifetime expired after 21.605 seconds: Server Do53:172.16.0.10@53 answered The DNS operation timed out.; Server Do53:8.8.8.8@53 answered The DNS operation timed out.; Server Do53:172.16.0.10@53 answered The DNS operation timed out.; Server Do53:8.8.8.8@53 answered The DNS operation timed out.; Server Do53:172.16.0.10@53 answered The DNS operation timed out.; Server Do53:8.8.8.8@53 answered The DNS operation timed out.; Server Do53:172.16.0.10@53 answered The DNS operation timed out.; Server Do53:8.8.8.8@53 answered The DNS operation timed out.; Server Do53:172.16.0.10@53 answered The DNS operation timed out.; Server Do53:8.8.8.8@53 answered The DNS operation timed out.
2024-08-06 12:46:28,316 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 12:46:33,187 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 12:49:45,766 - django.request - WARNING - Unauthorized: /api/get_resume/d54661b4-ada3-472b-93c5-f31f311c9598/
2024-08-06 12:50:07,236 - django.request - ERROR - Internal Server Error: /api/upload_resume/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1514, in _retryable_read
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1346, in _select_server
    server = topology.select_server(server_selector)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 244, in select_server
    return random.choice(self.select_servers(selector,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 202, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-yftqwrw-shard-00-00.6samspz.mongodb.net:27017: timed out,ac-yftqwrw-shard-00-02.6samspz.mongodb.net:27017: timed out,ac-yftqwrw-shard-00-01.6samspz.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 66b1cdcc73ba3609e446d44f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-yftqwrw-shard-00-00.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-00.6samspz.mongodb.net:27017: timed out')>, <ServerDescription ('ac-yftqwrw-shard-00-01.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-01.6samspz.mongodb.net:27017: timed out')>, <ServerDescription ('ac-yftqwrw-shard-00-02.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-02.6samspz.mongodb.net:27017: timed out')>]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\authentication.py", line 26, in authenticate
    user = User.objects.filter(candidate_id=candidate_id).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 692, in __getitem__
    for doc in clone:
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1531, in _retryable_read
    raise last_error
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\server.py", line 114, in run_operation
    reply = sock_info.receive_message(request_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\pool.py", line 753, in receive_message
    self._raise_connection_failure(error)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\pool.py", line 751, in receive_message
    return receive_message(self, request_id, self.max_message_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\network.py", line 200, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\network.py", line 297, in _receive_data_on_socket
    raise AutoReconnect("connection closed")
pymongo.errors.AutoReconnect: connection closed
2024-08-06 12:50:29,969 - django.request - ERROR - Internal Server Error: /api/get_resume/d54661b4-ada3-472b-93c5-f31f311c9598/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\authentication.py", line 26, in authenticate
    user = User.objects.filter(candidate_id=candidate_id).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 692, in __getitem__
    for doc in clone:
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-yftqwrw-shard-00-00.6samspz.mongodb.net:27017: timed out,ac-yftqwrw-shard-00-02.6samspz.mongodb.net:27017: timed out,ac-yftqwrw-shard-00-01.6samspz.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 66b1cdcc73ba3609e446d44f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-yftqwrw-shard-00-00.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-00.6samspz.mongodb.net:27017: timed out')>, <ServerDescription ('ac-yftqwrw-shard-00-01.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-01.6samspz.mongodb.net:27017: timed out')>, <ServerDescription ('ac-yftqwrw-shard-00-02.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-02.6samspz.mongodb.net:27017: timed out')>]>
2024-08-06 12:50:29,991 - django.request - ERROR - Internal Server Error: /api/upload_resume/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\authentication.py", line 26, in authenticate
    user = User.objects.filter(candidate_id=candidate_id).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 301, in first
    result = queryset[0]
             ~~~~~~~~^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\mongoengine\queryset\base.py", line 205, in __getitem__
    queryset._cursor[key],
    ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 692, in __getitem__
    for doc in clone:
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 504, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-yftqwrw-shard-00-00.6samspz.mongodb.net:27017: timed out,ac-yftqwrw-shard-00-02.6samspz.mongodb.net:27017: timed out,ac-yftqwrw-shard-00-01.6samspz.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 66b1cdcc73ba3609e446d44f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-yftqwrw-shard-00-00.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-00.6samspz.mongodb.net:27017: timed out')>, <ServerDescription ('ac-yftqwrw-shard-00-01.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-01.6samspz.mongodb.net:27017: timed out')>, <ServerDescription ('ac-yftqwrw-shard-00-02.6samspz.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-yftqwrw-shard-00-02.6samspz.mongodb.net:27017: timed out')>]>
2024-08-06 19:18:45,315 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:18:48,188 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:18:48,866 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:19:50,158 - django.request - WARNING - Bad Request: /api/signup/
2024-08-06 19:19:59,317 - django.request - WARNING - Bad Request: /api/signup/
2024-08-06 19:20:32,732 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\serializers.py changed, reloading.
2024-08-06 19:21:16,530 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:21:19,440 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:21:20,157 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:21:48,713 - django.request - WARNING - Bad Request: /api/signup/
2024-08-06 19:32:16,810 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:32:19,969 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:32:21,092 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:32:29,364 - django.request - WARNING - Bad Request: /api/login/
2024-08-06 19:32:51,274 - django.request - WARNING - Bad Request: /api/login/
2024-08-06 19:35:58,892 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:36:02,259 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:36:03,057 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:36:23,225 - django.request - WARNING - Unauthorized: /api/jobstatus/
2024-08-06 19:36:30,034 - django.request - WARNING - Bad Request: /api/jobstatus/
2024-08-06 19:37:00,842 - django.request - ERROR - Internal Server Error: /api/upload_resume/
Traceback (most recent call last):
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py", line 224, in post
    user_id = str(user.candidate_id)
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'candidate_id'
2024-08-06 19:37:39,444 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\authentication.py changed, reloading.
2024-08-06 19:37:43,248 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:37:44,443 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:46:24,110 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\authentication.py changed, reloading.
2024-08-06 19:46:27,094 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:46:28,309 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:46:34,981 - django.request - WARNING - Unauthorized: /api/upload_resume/
2024-08-06 19:49:25,000 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\views.py changed, reloading.
2024-08-06 19:49:28,283 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:49:28,922 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:50:30,066 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:50:34,707 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:50:35,283 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:50:39,611 - django.request - WARNING - Unauthorized: /api/signup/
2024-08-06 19:51:14,040 - django.utils.autoreload - INFO - C:\Users\Dhruv Adavadkar\OneDrive\Desktop\backendCode\backend\accounts\authentication.py changed, reloading.
2024-08-06 19:51:16,922 - connection - INFO - Pinged your deployment. You successfully connected to MongoDB!
2024-08-06 19:51:17,751 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-08-06 19:51:22,711 - django.request - WARNING - Bad Request: /api/signup/
